[workspace]
resolver = "2"
members = [
    "core",
    "dictionary"
]

[workspace.dependencies]
anyhow = "1.0.71"
once_cell = "1.17.1"
regex = "1.8.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
