[workspace]
resolver = "2"
members = [
    "core",
    "dictionary"
]

[workspace.dependencies]
anyhow = "1.0.75"
once_cell = "1.18.0"
regex = "1.9.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
