[package]
name = "zundamon"
version = "0.1.6"
edition = "2021"

[dependencies]
dictionary = { path = "../dictionary" }
anyhow = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
duct = "0.13.6"
hound = "3.5.0"
reqwest = "0.11.17"
songbird = { version = "0.3.2", features = ["builtin-queue"] }
strip-ansi-escapes = "0.1.1"
structopt = "0.3.26"
tokio = { version = "1.28.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["registry"] }
vvcore = "0.0.2"
walkdir = "2.3.3"
chrono-tz = "0.8.3"

[dependencies.serenity]
version = "0.11.5"
default-features = false
features = [
    "client",
    "model",
    "cache",
    "rustls_backend",
    "gateway",
    "voice-model",
    "collector"
]
