[package]
name = "dictionary"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
aho-corasick = "1.0.2"
deunicode = "1.3.3"
unic-emoji-char = "0.9.0"
