name: Rust

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
        - stable-x86_64-pc-windows-msvc
        - stable-x86_64-unknown-linux-gnu
        include:
        - { toolchain: stable-x86_64-pc-windows-msvc,  additional-target: '', os: windows-2019 }
        - { toolchain: stable-x86_64-unknown-linux-gnu, additional-target: x86_64-unknown-linux-musl, os: ubuntu-latest }

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup `${{ matrix.toolchain }}`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        target: ${{ matrix.additional-target }}
        default: true
        profile: minimal
        components: clippy

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast --verbose
